/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;
import resources.HTMLManager;
import resources.ResourceHTML;
import static resources.ResourceHTML.APPEND;
import static resources.ResourceHTML.HTML;
import tab.layout.LayoutTableItem;
import ui.ChromePreviewThread;
import static ui.NewsLetterUI.tabManager;

/**
 *
 * @author danielhwang
 */
public class TinyMce implements Runnable {

    private static Long sleepInterval = new Long(1000);

    LayoutTableItem lsItem;
    boolean preview;

    ResourceHTML basedHtmlOrg;

    public TinyMce(LayoutTableItem lsItem, boolean isPreview) {
        this.lsItem = lsItem;
        this.preview = isPreview;

        tab.Tab tab = tabManager.getCurrentTab();
        HTMLManager htmlManager = tab.getResourceManager().getHtmlManager();
        basedHtmlOrg = htmlManager.getBasedHTML();
    }

    public String getContents() {
        if (preview) {
            return lsItem.getPreview();
        } else {
            return lsItem.getTitle();
        }
    }

    public void setContents(String html) {
        if (preview) {
            lsItem.setPreview(html);
        } else {
            lsItem.setTitle(html);
        }
    }

    public void run() {
        String contents = getContents();
        ResourceHTML baseHtml = new ResourceHTML(basedHtmlOrg);
        baseHtml.insertContent(contents, "td[class=bodyContainer]", APPEND);

        if (System.getProperty("webdriver.chrome.driver") == null) {
            System.setProperty("webdriver.chrome.driver", "resources/common/chromedriverMac");
        }

        WebDriver driver = new ChromeDriver();
        //open TinyMCE
        Wait<WebDriver> wait = new WebDriverWait(driver, 30);
        String workingDir = System.getProperty("user.dir");
        String fileName = workingDir + "/resources/common/tinymce.html";
        driver.get("file://" + fileName);

        JavascriptExecutor javascriptExecutor = (JavascriptExecutor) driver;
        
        WebDriver driverDisplay = new ChromeDriver();
        String returnStr = (String) javascriptExecutor.executeScript("return tinyMCE.activeEditor.getContent({format : 'raw'});");
        //System.out.println(returnStr);

        String temp = "test/test.html";
        Document doc = Jsoup.parse(returnStr, "UTF-8");
        HTMLManager.saveHTML(doc, temp);
        driverDisplay.get("file://" + workingDir +"/" +temp);
        while (true) {
            try{
                Thread.sleep(sleepInterval);
                returnStr = (String) javascriptExecutor.executeScript("return tinyMCE.activeEditor.getContent({format : 'raw'});");
                //System.out.println(returnStr);
                
                //Insert To baseHTML and Save
                baseHtml.insertContent(returnStr, "td[class=bodyContainer]", HTML);
                HTMLManager.saveHTML(baseHtml.getDoc(), temp);
                
                driverDisplay.navigate().refresh();
            }catch (InterruptedException ex) {
                Logger.getLogger(ChromePreviewThread.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public static void main(String[] args) {
//        System.setProperty("webdriver.chrome.driver", "resources/common/chromedriverMac");
//
//        WebDriver driver = new ChromeDriver();
//        //EventFiringWebDriver eventDriver = new EventFiringWebDriver(driver);
//        
//        //EventHandler handler = new EventHandler();
//        //eventDriver.register(handler);
//        
//        
//        Wait<WebDriver> wait = new WebDriverWait(driver, 30);
//        String workingDir = System.getProperty("user.dir");
//        String fileName = workingDir + "/resources/common/tinymce.html";
//        
//        //eventDriver.get("file://" + fileName);
//        driver.get("file://" + fileName);
//        
//        String sgVal = (String) ((JavascriptExecutor)driver).executeScript("return isSaved();");
//        System.out.println(sgVal);
        //driver.get("file://" + fileName);

        //((JavascriptExecutor)driver).execute_script("tinyMCE.activeEditor.setContent('<h1>Yi Zeng</h1> TinyMCE')");
        //((JavascriptExecutor)driver).executeScript("tinyMCE.activeEditor.setContent('<h1>Yi Zeng</h1> TinyMCE')");
    }
    String test = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
            + " <head> \n"
            + "  <!-- NAME: 1:2 COLUMN --> \n"
            + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"> \n"
            + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \n"
            + "  <title></title> \n"
            + "  <style type=\"text/css\">\n"
            + "		body,#bodyTable,#bodyCell{\n"
            + "			height:100% !important;\n"
            + "			margin:0;\n"
            + "			padding:0;\n"
            + "			width:100% !important;\n"
            + "		}\n"
            + "		table{\n"
            + "			border-collapse:collapse;\n"
            + "		}\n"
            + "		img,a img{\n"
            + "			border:0;\n"
            + "			outline:none;\n"
            + "			text-decoration:none;\n"
            + "		}\n"
            + "		h1,h2,h3,h4,h5,h6{\n"
            + "			margin:0;\n"
            + "			padding:0;\n"
            + "		}\n"
            + "		p{\n"
            + "			margin:1em 0;\n"
            + "			padding:0;\n"
            + "		}\n"
            + "		a{\n"
            + "			word-wrap:break-word;\n"
            + "		}\n"
            + "		.ReadMsgBody{\n"
            + "			width:100%;\n"
            + "		}\n"
            + "		.ExternalClass{\n"
            + "			width:100%;\n"
            + "		}\n"
            + "		.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div{\n"
            + "			line-height:100%;\n"
            + "		}\n"
            + "		table,td{\n"
            + "			mso-table-lspace:0pt;\n"
            + "			mso-table-rspace:0pt;\n"
            + "		}\n"
            + "		#outlook a{\n"
            + "			padding:0;\n"
            + "		}\n"
            + "		img{\n"
            + "			-ms-interpolation-mode:bicubic;\n"
            + "		}\n"
            + "		body,table,td,p,a,li,blockquote{\n"
            + "			-ms-text-size-adjust:100%;\n"
            + "			-webkit-text-size-adjust:100%;\n"
            + "		}\n"
            + "		#templatePreheader,#templateHeader,#templateBody,#templateColumns,.templateColumn,#templateFooter{\n"
            + "			min-width:100%;\n"
            + "		}\n"
            + "		#bodyCell{\n"
            + "			padding:20px;\n"
            + "		}\n"
            + "		.mcnImage{\n"
            + "			vertical-align:bottom;\n"
            + "		}\n"
            + "		.mcnTextContent img{\n"
            + "			height:auto !important;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Page\n"
            + "	@section background style\n"
            + "	@tip Set the background color and top border for your email. You may want to choose colors that match your company's branding.\n"
            + "	*/\n"
            + "		body,#bodyTable{\n"
            + "			/*@editable*/background-color:#F2F2F2;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Page\n"
            + "	@section background style\n"
            + "	@tip Set the background color and top border for your email. You may want to choose colors that match your company's branding.\n"
            + "	*/\n"
            + "		#bodyCell{\n"
            + "			/*@editable*/border-top:0;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Page\n"
            + "	@section email border\n"
            + "	@tip Set the border for your email.\n"
            + "	*/\n"
            + "		#templateContainer{\n"
            + "			/*@editable*/border:0;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Page\n"
            + "	@section heading 1\n"
            + "	@tip Set the styling for all first-level headings in your emails. These should be the largest of your headings.\n"
            + "	@style heading 1\n"
            + "	*/\n"
            + "		h1{\n"
            + "			/*@editable*/color:#606060 !important;\n"
            + "			display:block;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:40px;\n"
            + "			/*@editable*/font-style:normal;\n"
            + "			/*@editable*/font-weight:bold;\n"
            + "			/*@editable*/line-height:125%;\n"
            + "			/*@editable*/letter-spacing:-1px;\n"
            + "			margin:0;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Page\n"
            + "	@section heading 2\n"
            + "	@tip Set the styling for all second-level headings in your emails.\n"
            + "	@style heading 2\n"
            + "	*/\n"
            + "		h2{\n"
            + "			/*@editable*/color:#404040 !important;\n"
            + "			display:block;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:26px;\n"
            + "			/*@editable*/font-style:normal;\n"
            + "			/*@editable*/font-weight:bold;\n"
            + "			/*@editable*/line-height:125%;\n"
            + "			/*@editable*/letter-spacing:-.75px;\n"
            + "			margin:0;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Page\n"
            + "	@section heading 3\n"
            + "	@tip Set the styling for all third-level headings in your emails.\n"
            + "	@style heading 3\n"
            + "	*/\n"
            + "		h3{\n"
            + "			/*@editable*/color:#606060 !important;\n"
            + "			display:block;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:18px;\n"
            + "			/*@editable*/font-style:normal;\n"
            + "			/*@editable*/font-weight:bold;\n"
            + "			/*@editable*/line-height:125%;\n"
            + "			/*@editable*/letter-spacing:-.5px;\n"
            + "			margin:0;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Page\n"
            + "	@section heading 4\n"
            + "	@tip Set the styling for all fourth-level headings in your emails. These should be the smallest of your headings.\n"
            + "	@style heading 4\n"
            + "	*/\n"
            + "		h4{\n"
            + "			/*@editable*/color:#808080 !important;\n"
            + "			display:block;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:16px;\n"
            + "			/*@editable*/font-style:normal;\n"
            + "			/*@editable*/font-weight:bold;\n"
            + "			/*@editable*/line-height:125%;\n"
            + "			/*@editable*/letter-spacing:normal;\n"
            + "			margin:0;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Preheader\n"
            + "	@section preheader style\n"
            + "	@tip Set the background color and borders for your email's preheader area.\n"
            + "	*/\n"
            + "		#templatePreheader{\n"
            + "			/*@editable*/background-color:#FFFFFF;\n"
            + "			/*@editable*/border-top:0;\n"
            + "			/*@editable*/border-bottom:0;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Preheader\n"
            + "	@section preheader text\n"
            + "	@tip Set the styling for your email's preheader text. Choose a size and color that is easy to read.\n"
            + "	*/\n"
            + "		.preheaderContainer .mcnTextContent,.preheaderContainer .mcnTextContent p{\n"
            + "			/*@editable*/color:#606060;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:11px;\n"
            + "			/*@editable*/line-height:125%;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Preheader\n"
            + "	@section preheader link\n"
            + "	@tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.\n"
            + "	*/\n"
            + "		.preheaderContainer .mcnTextContent a{\n"
            + "			/*@editable*/color:#606060;\n"
            + "			/*@editable*/font-weight:normal;\n"
            + "			/*@editable*/text-decoration:underline;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Header\n"
            + "	@section header style\n"
            + "	@tip Set the background color and borders for your email's header area.\n"
            + "	*/\n"
            + "		#templateHeader{\n"
            + "			/*@editable*/background-color:#FFFFFF;\n"
            + "			/*@editable*/border-top:0;\n"
            + "			/*@editable*/border-bottom:0;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Header\n"
            + "	@section header text\n"
            + "	@tip Set the styling for your email's header text. Choose a size and color that is easy to read.\n"
            + "	*/\n"
            + "		.headerContainer .mcnTextContent,.headerContainer .mcnTextContent p{\n"
            + "			/*@editable*/color:#606060;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:15px;\n"
            + "			/*@editable*/line-height:150%;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Header\n"
            + "	@section header link\n"
            + "	@tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.\n"
            + "	*/\n"
            + "		.headerContainer .mcnTextContent a{\n"
            + "			/*@editable*/color:#6DC6DD;\n"
            + "			/*@editable*/font-weight:normal;\n"
            + "			/*@editable*/text-decoration:underline;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Body\n"
            + "	@section body style\n"
            + "	@tip Set the background color and borders for your email's body area.\n"
            + "	*/\n"
            + "		#templateBody{\n"
            + "			/*@editable*/background-color:#FFFFFF;\n"
            + "			/*@editable*/border-top:0;\n"
            + "			/*@editable*/border-bottom:0;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Body\n"
            + "	@section body text\n"
            + "	@tip Set the styling for your email's body text. Choose a size and color that is easy to read.\n"
            + "	*/\n"
            + "		.bodyContainer .mcnTextContent,.bodyContainer .mcnTextContent p{\n"
            + "			/*@editable*/color:#606060;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:15px;\n"
            + "			/*@editable*/line-height:150%;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Body\n"
            + "	@section body link\n"
            + "	@tip Set the styling for your email's body links. Choose a color that helps them stand out from your text.\n"
            + "	*/\n"
            + "		.bodyContainer .mcnTextContent a{\n"
            + "			/*@editable*/color:#0909bd;\n"
            + "			/*@editable*/font-weight:normal;\n"
            + "			/*@editable*/text-decoration:underline;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Columns\n"
            + "	@section column style\n"
            + "	@tip Set the background color and borders for your email's columns area.\n"
            + "	*/\n"
            + "		#templateColumns{\n"
            + "			/*@editable*/background-color:#FFFFFF;\n"
            + "			/*@editable*/border-top:0;\n"
            + "			/*@editable*/border-bottom:0;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Columns\n"
            + "	@section left column text\n"
            + "	@tip Set the styling for your email's left column text. Choose a size and color that is easy to read.\n"
            + "	*/\n"
            + "		.leftColumnContainer .mcnTextContent,.leftColumnContainer .mcnTextContent p{\n"
            + "			/*@editable*/color:#606060;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:15px;\n"
            + "			/*@editable*/line-height:150%;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Columns\n"
            + "	@section left column link\n"
            + "	@tip Set the styling for your email's left column links. Choose a color that helps them stand out from your text.\n"
            + "	*/\n"
            + "		.leftColumnContainer .mcnTextContent a{\n"
            + "			/*@editable*/color:#0000bd;\n"
            + "			/*@editable*/font-weight:normal;\n"
            + "			/*@editable*/text-decoration:underline;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Columns\n"
            + "	@section right column text\n"
            + "	@tip Set the styling for your email's right column text. Choose a size and color that is easy to read.\n"
            + "	*/\n"
            + "		.rightColumnContainer .mcnTextContent,.rightColumnContainer .mcnTextContent p{\n"
            + "			/*@editable*/color:#606060;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:15px;\n"
            + "			/*@editable*/line-height:150%;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Columns\n"
            + "	@section right column link\n"
            + "	@tip Set the styling for your email's right column links. Choose a color that helps them stand out from your text.\n"
            + "	*/\n"
            + "		.rightColumnContainer .mcnTextContent a{\n"
            + "			/*@editable*/color:#6c6cdd;\n"
            + "			/*@editable*/font-weight:normal;\n"
            + "			/*@editable*/text-decoration:underline;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Footer\n"
            + "	@section footer style\n"
            + "	@tip Set the background color and borders for your email's footer area.\n"
            + "	*/\n"
            + "		#templateFooter{\n"
            + "			/*@editable*/background-color:#FFFFFF;\n"
            + "			/*@editable*/border-top:0;\n"
            + "			/*@editable*/border-bottom:0;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Footer\n"
            + "	@section footer text\n"
            + "	@tip Set the styling for your email's footer text. Choose a size and color that is easy to read.\n"
            + "	*/\n"
            + "		.footerContainer .mcnTextContent,.footerContainer .mcnTextContent p{\n"
            + "			/*@editable*/color:#606060;\n"
            + "			/*@editable*/font-family:Helvetica;\n"
            + "			/*@editable*/font-size:11px;\n"
            + "			/*@editable*/line-height:150%;\n"
            + "			/*@editable*/text-align:left;\n"
            + "		}\n"
            + "	/*\n"
            + "	@tab Footer\n"
            + "	@section footer link\n"
            + "	@tip Set the styling for your email's footer links. Choose a color that helps them stand out from your text.\n"
            + "	*/\n"
            + "		.footerContainer .mcnTextContent a{\n"
            + "			/*@editable*/color:#606060;\n"
            + "			/*@editable*/font-weight:normal;\n"
            + "			/*@editable*/text-decoration:underline;\n"
            + "		}\n"
            + "	@media only screen and (max-width: 480px){\n"
            + "		body,table,td,p,a,li,blockquote{\n"
            + "			-webkit-text-size-adjust:none !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		body{\n"
            + "			width:100% !important;\n"
            + "			min-width:100% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[id=bodyCell]{\n"
            + "			padding:10px !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		table[class=mcnTextContentContainer]{\n"
            + "			width:100% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		.mcnBoxedTextContentContainer{\n"
            + "			max-width:100% !important;\n"
            + "			min-width:100% !important;\n"
            + "			width:100% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		table[class=mcpreview-image-uploader]{\n"
            + "			width:100% !important;\n"
            + "			display:none !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		img[class=mcnImage]{\n"
            + "			width:100% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		table[class=mcnImageGroupContentContainer]{\n"
            + "			width:100% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=mcnImageGroupContent]{\n"
            + "			padding:9px !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=mcnImageGroupBlockInner]{\n"
            + "			padding-bottom:0 !important;\n"
            + "			padding-top:0 !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		tbody[class=mcnImageGroupBlockOuter]{\n"
            + "			padding-bottom:9px !important;\n"
            + "			padding-top:9px !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		table[class=mcnCaptionTopContent],table[class=mcnCaptionBottomContent]{\n"
            + "			width:100% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		table[class=mcnCaptionLeftTextContentContainer],table[class=mcnCaptionRightTextContentContainer],table[class=mcnCaptionLeftImageContentContainer],table[class=mcnCaptionRightImageContentContainer],table[class=mcnImageCardLeftTextContentContainer],table[class=mcnImageCardRightTextContentContainer]{\n"
            + "			width:100% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=mcnImageCardLeftImageContent],td[class=mcnImageCardRightImageContent]{\n"
            + "			padding-right:18px !important;\n"
            + "			padding-left:18px !important;\n"
            + "			padding-bottom:0 !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=mcnImageCardBottomImageContent]{\n"
            + "			padding-bottom:9px !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=mcnImageCardTopImageContent]{\n"
            + "			padding-top:18px !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		table[class=mcnCaptionLeftContentOuter] td[class=mcnTextContent],table[class=mcnCaptionRightContentOuter] td[class=mcnTextContent]{\n"
            + "			padding-top:9px !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=mcnCaptionBlockInner] table[class=mcnCaptionTopContent]:last-child td[class=mcnTextContent]{\n"
            + "			padding-top:18px !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=mcnBoxedTextContentColumn]{\n"
            + "			padding-left:18px !important;\n"
            + "			padding-right:18px !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=columnsContainer]{\n"
            + "			display:block !important;\n"
            + "			max-width:600px !important;\n"
            + "			width:100% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=mcnTextContent]{\n"
            + "			padding-right:18px !important;\n"
            + "			padding-left:18px !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section template width\n"
            + "	@tip Make the template fluid for portrait or landscape view adaptability. If a fluid layout doesn't work for you, set the width to 300px instead.\n"
            + "	*/\n"
            + "		table[id=templateContainer],table[id=templatePreheader],table[id=templateHeader],table[id=templateColumns],table[class=templateColumn],table[id=templateBody],table[id=templateFooter]{\n"
            + "			/*@tab Mobile Styles\n"
            + "@section template width\n"
            + "@tip Make the template fluid for portrait or landscape view adaptability. If a fluid layout doesn't work for you, set the width to 300px instead.*/max-width:600px !important;\n"
            + "			/*@editable*/width:100% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section heading 1\n"
            + "	@tip Make the first-level headings larger in size for better readability on small screens.\n"
            + "	*/\n"
            + "		h1{\n"
            + "			/*@editable*/font-size:24px !important;\n"
            + "			/*@editable*/line-height:125% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section heading 2\n"
            + "	@tip Make the second-level headings larger in size for better readability on small screens.\n"
            + "	*/\n"
            + "		h2{\n"
            + "			/*@editable*/font-size:20px !important;\n"
            + "			/*@editable*/line-height:125% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section heading 3\n"
            + "	@tip Make the third-level headings larger in size for better readability on small screens.\n"
            + "	*/\n"
            + "		h3{\n"
            + "			/*@editable*/font-size:18px !important;\n"
            + "			/*@editable*/line-height:125% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section heading 4\n"
            + "	@tip Make the fourth-level headings larger in size for better readability on small screens.\n"
            + "	*/\n"
            + "		h4{\n"
            + "			/*@editable*/font-size:16px !important;\n"
            + "			/*@editable*/line-height:125% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section Boxed Text\n"
            + "	@tip Make the boxed text larger in size for better readability on small screens. We recommend a font size of at least 16px.\n"
            + "	*/\n"
            + "		table[class=mcnBoxedTextContentContainer] td[class=mcnTextContent],td[class=mcnBoxedTextContentContainer] td[class=mcnTextContent] p{\n"
            + "			/*@editable*/font-size:18px !important;\n"
            + "			/*@editable*/line-height:125% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section Preheader Visibility\n"
            + "	@tip Set the visibility of the email's preheader on small screens. You can hide it to save space.\n"
            + "	*/\n"
            + "		table[id=templatePreheader]{\n"
            + "			/*@editable*/display:none !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section Preheader Text\n"
            + "	@tip Make the preheader text larger in size for better readability on small screens.\n"
            + "	*/\n"
            + "		td[class=preheaderContainer] td[class=mcnTextContent],td[class=preheaderContainer] td[class=mcnTextContent] p{\n"
            + "			/*@editable*/font-size:14px !important;\n"
            + "			/*@editable*/line-height:115% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section Header Text\n"
            + "	@tip Make the header text larger in size for better readability on small screens.\n"
            + "	*/\n"
            + "		td[class=headerContainer] td[class=mcnTextContent],td[class=headerContainer] td[class=mcnTextContent] p{\n"
            + "			/*@editable*/font-size:18px !important;\n"
            + "			/*@editable*/line-height:125% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section Body Text\n"
            + "	@tip Make the body text larger in size for better readability on small screens. We recommend a font size of at least 16px.\n"
            + "	*/\n"
            + "		td[class=bodyContainer] td[class=mcnTextContent],td[class=bodyContainer] td[class=mcnTextContent] p{\n"
            + "			/*@editable*/font-size:18px !important;\n"
            + "			/*@editable*/line-height:125% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section Left Column Text\n"
            + "	@tip Make the left column text larger in size for better readability on small screens. We recommend a font size of at least 16px.\n"
            + "	*/\n"
            + "		td[class=leftColumnContainer] td[class=mcnTextContent],td[class=leftColumnContainer] td[class=mcnTextContent] p{\n"
            + "			/*@editable*/font-size:18px !important;\n"
            + "			/*@editable*/line-height:125% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section Right Column Text\n"
            + "	@tip Make the right column text larger in size for better readability on small screens. We recommend a font size of at least 16px.\n"
            + "	*/\n"
            + "		td[class=rightColumnContainer] td[class=mcnTextContent],td[class=rightColumnContainer] td[class=mcnTextContent] p{\n"
            + "			/*@editable*/font-size:18px !important;\n"
            + "			/*@editable*/line-height:125% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "	/*\n"
            + "	@tab Mobile Styles\n"
            + "	@section footer text\n"
            + "	@tip Make the body content text larger in size for better readability on small screens.\n"
            + "	*/\n"
            + "		td[class=footerContainer] td[class=mcnTextContent],td[class=footerContainer] td[class=mcnTextContent] p{\n"
            + "			/*@editable*/font-size:14px !important;\n"
            + "			/*@editable*/line-height:115% !important;\n"
            + "		}\n"
            + "\n"
            + "}	@media only screen and (max-width: 480px){\n"
            + "		td[class=footerContainer] a[class=utilityLink]{\n"
            + "			display:block !important;\n"
            + "		}\n"
            + "\n"
            + "}</style>\n"
            + " </head> \n"
            + " <body leftmargin=\"0\" marginwidth=\"0\" topmargin=\"0\" marginheight=\"0\" offset=\"0\"> \n"
            + "  <center> \n"
            + "   <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\" id=\"bodyTable\"> \n"
            + "    <tbody>\n"
            + "     <tr> \n"
            + "      <td align=\"center\" valign=\"top\" id=\"bodyCell\"> \n"
            + "       <!-- BEGIN TEMPLATE // --> \n"
            + "       <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"templateContainer\"> \n"
            + "        <tbody>\n"
            + "         <tr> \n"
            + "          <td align=\"center\" valign=\"top\"> \n"
            + "           <!-- BEGIN PREHEADER // --> \n"
            + "           <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"templatePreheader\"> \n"
            + "            <tbody>\n"
            + "             <tr> \n"
            + "              <td valign=\"top\" class=\"preheaderContainer\" style=\"padding-top:9px;\"></td> \n"
            + "             </tr> \n"
            + "            </tbody>\n"
            + "           </table> \n"
            + "           <!-- // END PREHEADER --> </td> \n"
            + "         </tr> \n"
            + "         <tr> \n"
            + "          <td align=\"center\" valign=\"top\"> \n"
            + "           <!-- BEGIN HEADER // --> \n"
            + "           <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"templateHeader\"> \n"
            + "            <tbody>\n"
            + "             <tr> \n"
            + "              <td valign=\"top\" class=\"headerContainer\">\n"
            + "               <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnCaptionBlock\"> \n"
            + "                <tbody class=\"mcnCaptionBlockOuter\"> \n"
            + "                 <tr> \n"
            + "                  <td class=\"mcnCaptionBlockInner\" valign=\"top\" style=\"padding:9px;\"> \n"
            + "                   <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnCaptionRightContentOuter\" width=\"100%\"> \n"
            + "                    <tbody>\n"
            + "                     <tr> \n"
            + "                      <td valign=\"top\" class=\"mcnCaptionRightContentInner\" style=\"padding:0 9px ;\"> \n"
            + "                       <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnCaptionRightImageContentContainer\"> \n"
            + "                        <tbody>\n"
            + "                         <tr> \n"
            + "                          <td class=\"mcnCaptionRightImageContent\" valign=\"top\"> <img alt=\"I Know First\" src=\"https://gallery.mailchimp.com/f00d3ffe6a71a2b38671432df/images/758c4e92-a47c-44aa-b2e8-342c8e247bc3.jpg\" width=\"263\" style=\"max-width:600px;\" class=\"mcnImage\"> </td> \n"
            + "                         </tr> \n"
            + "                        </tbody>\n"
            + "                       </table> \n"
            + "                       <table class=\"mcnCaptionRightTextContentContainer\" align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"263\"> \n"
            + "                        <tbody>\n"
            + "                         <tr> \n"
            + "                          <td valign=\"top\" class=\"mcnTextContent\" style=\"text-align: center;\"> </td> \n"
            + "                         </tr> \n"
            + "                        </tbody>\n"
            + "                       </table> </td> \n"
            + "                     </tr> \n"
            + "                    </tbody>\n"
            + "                   </table> </td> \n"
            + "                 </tr> \n"
            + "                </tbody> \n"
            + "               </table>\n"
            + "               <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\" style=\"min-width:100%;\"> \n"
            + "                <tbody class=\"mcnTextBlockOuter\"> \n"
            + "                 <tr> \n"
            + "                  <td valign=\"top\" class=\"mcnTextBlockInner\" style=\"padding-top:9px;\"> \n"
            + "                   <!--[if mso]>\n"
            + "				<table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"width:100%;\">\n"
            + "				<tr>\n"
            + "				<![endif]--> \n"
            + "                   <!--[if mso]>\n"
            + "				<td valign=\"top\" width=\"599\" style=\"width:599px;\">\n"
            + "				<![endif]--> \n"
            + "                   <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:100%; min-width:100%;\" width=\"100%\" class=\"mcnTextContentContainer\"> \n"
            + "                    <tbody>\n"
            + "                     <tr> \n"
            + "                      <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:0; padding-right:18px; padding-bottom:9px; padding-left:18px;\"> \n"
            + "                       <div style=\"font-family: 'Trebuchet MS'; line-height: normal; text-align: center;\"> \n"
            + "                        <div style=\"font-family: 'Trebuchet MS'; line-height: normal; text-align: center;\">\n"
            + "                         <br> \n"
            + "                         <span style=\"color:#0000FF\"><strong>Stock Market Forecast Based on Our&nbsp;State-Of-The-Art&nbsp;Predictive Algorithm</strong></span>\n"
            + "                        </div> \n"
            + "                        <div style=\"color: #000000;font-family: 'Trebuchet MS';font-size: 11px;line-height: normal;text-align: center;\">\n"
            + "                         <span style=\"font-size:14px\"><span style=\"color:#FFA500\"><strong style=\"color: #289443;\">- <span id=\"newsLetterDate\">January 22nd, 2017</span>&nbsp;-</strong></span></span>\n"
            + "                        </div> \n"
            + "                       </div> </td> \n"
            + "                     </tr> \n"
            + "                    </tbody>\n"
            + "                   </table> \n"
            + "                   <!--[if mso]>\n"
            + "				</td>\n"
            + "				<![endif]--> \n"
            + "                   <!--[if mso]>\n"
            + "				</tr>\n"
            + "				</table>\n"
            + "				<![endif]--> </td> \n"
            + "                 </tr> \n"
            + "                </tbody> \n"
            + "               </table></td> \n"
            + "             </tr> \n"
            + "            </tbody>\n"
            + "           </table> \n"
            + "           <!-- // END HEADER --> </td> \n"
            + "         </tr> \n"
            + "         <tr> \n"
            + "          <td align=\"center\" valign=\"top\"> \n"
            + "           <!-- BEGIN BODY // --> \n"
            + "           <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"templateBody\"> \n"
            + "            <tbody>\n"
            + "             <tr> \n"
            + "              <td valign=\"top\" class=\"bodyContainer\">   \n"
            + "               <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnbuttonblock\" style=\"min-width:100%;\"> \n"
            + "                <tbody class=\"mcnbuttonblockouter\"> \n"
            + "                 <tr> \n"
            + "                  <td valign=\"top\" align=\"center\" class=\"mcnbuttonblockinner\" style=\"padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px;\"> \n"
            + "                   <table name=\"mainBody\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnbuttoncontentcontainer\" border-radius=\"5px\" style=\"border-collapse:separate !important;border-top-width:2px;border-top-style:solid;border-top-color:#707070;border-right-width:2px;border-right-style:solid;border-right-color:#707070;border-bottom-width:2px;border-bottom-style:solid;border-bottom-color:#707070;border-left-width:2px;border-left-style:solid;border-left-color:#707070;background-color:#210EF1;\"> \n"
            + "                    <tbody> \n"
            + "                     <tr> \n"
            + "                      <td align=\"center\" valign=\"middle\" class=\"mcnbuttoncontent\" style=\"font-family: Lucida Sans Unicode ,  Lucida Grande , sans-serif;padding-top:24px;padding-right:24px;padding-bottom:24px;padding-left:24px;font-size:25.71px;\"><a class=\"mcnbutton\" title=\"WOWOWOW good LUCK\" href=\"http://lpage.iknowfirst.com/\" target=\"_blank\" style=\"font-weight:bold;letter-spacing:0px;line-height:100%;text-align:center;text-decoration:none;color:#FFFFFF;\">WOWOWOW good LUCK</a></td> \n"
            + "                     </tr> \n"
            + "                    </tbody> \n"
            + "                   </table></td> \n"
            + "                 </tr> \n"
            + "                </tbody> \n"
            + "               </table>  </td> \n"
            + "             </tr> \n"
            + "            </tbody>\n"
            + "           </table> \n"
            + "           <!-- // END BODY --> </td> \n"
            + "         </tr> \n"
            + "         <tr> \n"
            + "          <td align=\"center\" valign=\"top\"> \n"
            + "           <!-- BEGIN COLUMNS // --> \n"
            + "           <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"templateColumns\"> \n"
            + "            <tbody>\n"
            + "             <tr> \n"
            + "              <td align=\"left\" valign=\"top\" class=\"columnsContainer\" width=\"50%\"> \n"
            + "               <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"templateColumn\"> \n"
            + "                <tbody>\n"
            + "                 <tr> \n"
            + "                  <td valign=\"top\" class=\"leftColumnContainer\"></td> \n"
            + "                 </tr> \n"
            + "                </tbody>\n"
            + "               </table> </td> \n"
            + "              <td align=\"left\" valign=\"top\" class=\"columnsContainer\" width=\"50%\"> \n"
            + "               <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"templateColumn\"> \n"
            + "                <tbody>\n"
            + "                 <tr> \n"
            + "                  <td valign=\"top\" class=\"rightColumnContainer\"></td> \n"
            + "                 </tr> \n"
            + "                </tbody>\n"
            + "               </table> </td> \n"
            + "             </tr> \n"
            + "            </tbody>\n"
            + "           </table> \n"
            + "           <!-- // END COLUMNS --> </td> \n"
            + "         </tr> \n"
            + "         <tr> \n"
            + "          <td align=\"center\" valign=\"top\"> \n"
            + "           <!-- BEGIN FOOTER // --> \n"
            + "           <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"templateFooter\"> \n"
            + "            <tbody>\n"
            + "             <tr> \n"
            + "              <td valign=\"top\" class=\"footerContainer\" style=\"padding-bottom:9px;\">\n"
            + "               <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnDividerBlock\" style=\"min-width:100%;\"> \n"
            + "                <tbody class=\"mcnDividerBlockOuter\"> \n"
            + "                 <tr> \n"
            + "                  <td class=\"mcnDividerBlockInner\" style=\"min-width: 100%; padding: 0.5px 18px;\"> \n"
            + "                   <table class=\"mcnDividerContent\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"min-width: 100%;border-top: 1px solid #999999;\"> \n"
            + "                    <tbody>\n"
            + "                     <tr> \n"
            + "                      <td> <span></span> </td> \n"
            + "                     </tr> \n"
            + "                    </tbody>\n"
            + "                   </table> \n"
            + "                   <!--            \n"
            + "                <td class=\"mcnDividerBlockInner\" style=\"padding: 18px;\">\n"
            + "                <hr class=\"mcnDividerContent\" style=\"border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;\" />\n"
            + "--> </td> \n"
            + "                 </tr> \n"
            + "                </tbody> \n"
            + "               </table>\n"
            + "               <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\" style=\"min-width:100%;\"> \n"
            + "                <tbody class=\"mcnTextBlockOuter\"> \n"
            + "                 <tr> \n"
            + "                  <td valign=\"top\" class=\"mcnTextBlockInner\" style=\"padding-top:9px;\"> \n"
            + "                   <!--[if mso]>\n"
            + "				<table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"width:100%;\">\n"
            + "				<tr>\n"
            + "				<![endif]--> \n"
            + "                   <!--[if mso]>\n"
            + "				<td valign=\"top\" width=\"600\" style=\"width:600px;\">\n"
            + "				<![endif]--> \n"
            + "                   <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:100%; min-width:100%;\" width=\"100%\" class=\"mcnTextContentContainer\"> \n"
            + "                    <tbody>\n"
            + "                     <tr> \n"
            + "                      <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:0; padding-right:18px; padding-bottom:9px; padding-left:18px;\"> \n"
            + "                       <div dir=\"ltr\" style=\"text-align: center;\">\n"
            + "                        <em>Copyright © 2017 &nbsp;I Know First: Daily Market Forecast&nbsp;All rights reserved.</em>\n"
            + "                       </div> </td> \n"
            + "                     </tr> \n"
            + "                    </tbody>\n"
            + "                   </table> \n"
            + "                   <!--[if mso]>\n"
            + "				</td>\n"
            + "				<![endif]--> \n"
            + "                   <!--[if mso]>\n"
            + "				</tr>\n"
            + "				</table>\n"
            + "				<![endif]--> </td> \n"
            + "                 </tr> \n"
            + "                </tbody> \n"
            + "               </table></td> \n"
            + "             </tr> \n"
            + "            </tbody>\n"
            + "           </table> \n"
            + "           <!-- // END FOOTER --> </td> \n"
            + "         </tr> \n"
            + "        </tbody>\n"
            + "       </table> \n"
            + "       <!-- // END TEMPLATE --> </td> \n"
            + "     </tr> \n"
            + "    </tbody>\n"
            + "   </table> \n"
            + "  </center>  \n"
            + " </body>\n"
            + "</html>";
}
