/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.io.PrintStream;
import tab.TabManager;
import static ui.FormManaqer.*;
import static ui.NewsLetterUI.jColorChooser;


/**
 *
 * @author Daniel
 */
public class NewsLetterUI extends javax.swing.JFrame {
    
    public static TabManager tabManager;
    public static PrintStream con;
    public static ToolbarCustomizing previewHtmlEditor;
    public static ToolbarCustomizing titleHtmlEditor;
    /**
     * Creates new form BodyFrame
     */
    
    public NewsLetterUI() {
        
        
        
        initComponents();
        
//        openConsole();
        tabManager = new TabManager(jTabbedLanguageTab);
        
        previewHtmlEditor = new ToolbarCustomizing();
        previewHtmlEditor.create(jPanelHtmlPreviewButtonsForm);
        
        titleHtmlEditor = new ToolbarCustomizing();
        titleHtmlEditor.create(jPanelHtmlTitleButtonsForm);
        
        setEnabledLayoutForm(false);
        //setEnabledLayoutButtons(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserLayout = new javax.swing.JFileChooser();
        jDialogAddLayoutItem = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jFrameConsoleBox = new javax.swing.JFrame();
        jScrollPaneMessage = new javax.swing.JScrollPane();
        jTextAreaMessageBox = new javax.swing.JTextArea();
        jPanelHtmlTitleButtonsForm = new javax.swing.JPanel();
        jButtonTitleOk = new javax.swing.JButton();
        jButtonTitleCancel = new javax.swing.JButton();
        jPanelHtmlPreviewButtonsForm = new javax.swing.JPanel();
        jButtonPreviewOk = new javax.swing.JButton();
        jButtonPreviewCancel = new javax.swing.JButton();
        jComboBoxLayoutTypeChoosen = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPaneLayoutTitle = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPaneLayoutPreview = new javax.swing.JEditorPane();
        jDialogColorChooser = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jColorChooser = new javax.swing.JColorChooser();
        jPanel9 = new javax.swing.JPanel();
        jTextFieldColorPicked = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanelRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelProgramName = new javax.swing.JLabel();
        jCheckBoxGenerateThis = new javax.swing.JCheckBox();
        jTabbedLanguageTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelCardForm = new javax.swing.JPanel();
        jPanelForecastSectionForm = new javax.swing.JPanel();
        jPanelForecastSectionTop = new javax.swing.JPanel();
        jTextFieldChoosingCSVDir = new javax.swing.JTextField();
        jButtonChooseDir = new javax.swing.JButton();
        jButtonOpenForecastCSV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelForecastSectionBody = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEnglishLink = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButtonEnglishLinkSubmit = new javax.swing.JButton();
        jPanelForecastSectionBottom = new javax.swing.JPanel();
        jButtonSwitchToLayout = new javax.swing.JButton();
        jPanelLayoutSectionForm = new javax.swing.JPanel();
        jPanelLayoutSectionTop = new javax.swing.JPanel();
        jButtonLayoutSectionAdd = new javax.swing.JButton();
        jButtonLayoutSectionSub = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLayoutTypeChoice = new javax.swing.JComboBox<>();
        jButtonSelectDeslectAll = new javax.swing.JButton();
        jXDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jPanelLayoutSectionBody = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerPosition = new javax.swing.JSpinner();
        jButtonEditLayoutPreview = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaParameters = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButtonEditLayoutTitle = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonLayoutSectionLoadLayout = new javax.swing.JButton();
        jButtonLayoutSectionSaveLayout = new javax.swing.JButton();
        jButtonLayoutSectionGenerateNewsletter = new javax.swing.JButton();
        jButtonSaveNewsletter = new javax.swing.JButton();
        jButtonColorPicker = new javax.swing.JButton();
        jButtonLayoutSectionLoadLayoutNPreview = new javax.swing.JButton();
        jButtonEditLayoutPreviewNewsletter = new javax.swing.JButton();
        jPanelLayoutSectionBottom = new javax.swing.JPanel();
        jButtonSwitchToForecast = new javax.swing.JButton();

        jFileChooserLayout.setCurrentDirectory(new File(System.getProperty("user.dir")));

        jLabel8.setText("Type");

        jTextField1.setText("jTextField1");

        jLabel11.setText("Options");

        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setText("Add");
        jPanel5.add(jButton2);

        jButton3.setText("Cancel");
        jPanel5.add(jButton3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel8, jTextField1, jTextField3});

        jTabbedPane1.addTab("Manual Item", jPanel3);

        jLabel12.setText("XML File Directory");

        jTextField4.setText("jTextField4");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/open.png"))); // NOI18N

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jButton4.setText("Add");
        jPanel6.add(jButton4);

        jButton5.setText("Cancel");
        jPanel6.add(jButton5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField4)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Import Wordpress XML", jPanel4);

        javax.swing.GroupLayout jDialogAddLayoutItemLayout = new javax.swing.GroupLayout(jDialogAddLayoutItem.getContentPane());
        jDialogAddLayoutItem.getContentPane().setLayout(jDialogAddLayoutItemLayout);
        jDialogAddLayoutItemLayout.setHorizontalGroup(
            jDialogAddLayoutItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jDialogAddLayoutItemLayout.setVerticalGroup(
            jDialogAddLayoutItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jFrameConsoleBox.getContentPane().setLayout(new javax.swing.BoxLayout(jFrameConsoleBox.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTextAreaMessageBox.setEditable(false);
        jTextAreaMessageBox.setColumns(20);
        jTextAreaMessageBox.setLineWrap(true);
        jTextAreaMessageBox.setRows(5);
        jTextAreaMessageBox.setWrapStyleWord(true);
        jScrollPaneMessage.setViewportView(jTextAreaMessageBox);

        jFrameConsoleBox.getContentPane().add(jScrollPaneMessage);

        jButtonTitleOk.setText("Ok");
        jButtonTitleOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTitleOkActionPerformed(evt);
            }
        });
        jPanelHtmlTitleButtonsForm.add(jButtonTitleOk);

        jButtonTitleCancel.setText("Cancel");
        jButtonTitleCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTitleCancelActionPerformed(evt);
            }
        });
        jPanelHtmlTitleButtonsForm.add(jButtonTitleCancel);

        jButtonPreviewOk.setText("Ok");
        jButtonPreviewOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviewOkActionPerformed(evt);
            }
        });
        jPanelHtmlPreviewButtonsForm.add(jButtonPreviewOk);

        jButtonPreviewCancel.setText("Cancel");
        jButtonPreviewCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviewCancelActionPerformed(evt);
            }
        });
        jPanelHtmlPreviewButtonsForm.add(jButtonPreviewCancel);

        jComboBoxLayoutTypeChoosen.setModel(new javax.swing.DefaultComboBoxModel<>(layoutTypeList));

        jScrollPane4.setViewportView(jEditorPaneLayoutTitle);

        jScrollPane5.setViewportView(jEditorPaneLayoutPreview);

        jDialogColorChooser.setMinimumSize(new java.awt.Dimension(636, 356));

        jColorChooser.setPreferredSize(new java.awt.Dimension(800, 356));
        jColorChooser.getSelectionModel().addChangeListener(new ColorSelection());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jColorChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jColorChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
        );

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jTextFieldColorPicked.setText("Select Color And Copy Paste The Generated Code");
        jPanel9.add(jTextFieldColorPicked);

        javax.swing.GroupLayout jDialogColorChooserLayout = new javax.swing.GroupLayout(jDialogColorChooser.getContentPane());
        jDialogColorChooser.getContentPane().setLayout(jDialogColorChooserLayout);
        jDialogColorChooserLayout.setHorizontalGroup(
            jDialogColorChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogColorChooserLayout.setVerticalGroup(
            jDialogColorChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogColorChooserLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Newsletter Automation");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1050, 800));
        setSize(new java.awt.Dimension(1050, 800));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1050, 100));

        jPanelRoot.setPreferredSize(new java.awt.Dimension(1020, 729));
        jPanelRoot.setLayout(new javax.swing.BoxLayout(jPanelRoot, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(1014, 29));

        jLabelProgramName.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabelProgramName.setText("Newsletter Automation");
        jLabelProgramName.setToolTipText("");

        jCheckBoxGenerateThis.setText("Generate in This Language");
        jCheckBoxGenerateThis.setEnabled(false);
        jCheckBoxGenerateThis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGenerateThisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxGenerateThis)
                .addGap(0, 573, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelProgramName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxGenerateThis))
        );

        jPanelRoot.add(jPanel2);

        jTabbedLanguageTab.setPreferredSize(new java.awt.Dimension(1014, 249));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 217));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        jTabbedLanguageTab.addTab("tab1", jPanel1);

        jPanelRoot.add(jTabbedLanguageTab);

        jPanelCardForm.setLayout(new java.awt.CardLayout(5, 5));

        jPanelForecastSectionForm.setPreferredSize(new java.awt.Dimension(1004, 400));

        jPanelForecastSectionTop.setPreferredSize(new java.awt.Dimension(1000, 100));

        jTextFieldChoosingCSVDir.setEnabled(false);

        jButtonChooseDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/open.png"))); // NOI18N
        jButtonChooseDir.setEnabled(false);
        jButtonChooseDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseDirActionPerformed(evt);
            }
        });

        jButtonOpenForecastCSV.setText("Open Forecast");
        jButtonOpenForecastCSV.setEnabled(false);
        jButtonOpenForecastCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenForecastCSVActionPerformed(evt);
            }
        });

        jLabel1.setText("CSV Directory");
        jLabel1.setEnabled(false);

        javax.swing.GroupLayout jPanelForecastSectionTopLayout = new javax.swing.GroupLayout(jPanelForecastSectionTop);
        jPanelForecastSectionTop.setLayout(jPanelForecastSectionTopLayout);
        jPanelForecastSectionTopLayout.setHorizontalGroup(
            jPanelForecastSectionTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelForecastSectionTopLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldChoosingCSVDir, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonChooseDir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOpenForecastCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelForecastSectionTopLayout.setVerticalGroup(
            jPanelForecastSectionTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForecastSectionTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldChoosingCSVDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelForecastSectionTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonOpenForecastCSV)
                .addComponent(jButtonChooseDir))
        );

        jPanelForecastSectionTopLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonChooseDir, jButtonOpenForecastCSV, jTextFieldChoosingCSVDir});

        jPanelForecastSectionBody.setPreferredSize(new java.awt.Dimension(1000, 100));

        jTextAreaEnglishLink.setColumns(20);
        jTextAreaEnglishLink.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEnglishLink);

        jLabel2.setText("Add Link From English site");

        jButtonEnglishLinkSubmit.setText("Submit");
        jButtonEnglishLinkSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnglishLinkSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelForecastSectionBodyLayout = new javax.swing.GroupLayout(jPanelForecastSectionBody);
        jPanelForecastSectionBody.setLayout(jPanelForecastSectionBodyLayout);
        jPanelForecastSectionBodyLayout.setHorizontalGroup(
            jPanelForecastSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForecastSectionBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnglishLinkSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelForecastSectionBodyLayout.setVerticalGroup(
            jPanelForecastSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelForecastSectionBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelForecastSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelForecastSectionBodyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEnglishLinkSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelForecastSectionBodyLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanelForecastSectionBottom.setPreferredSize(new java.awt.Dimension(1000, 100));

        jButtonSwitchToLayout.setText("Switch To Layout");
        jButtonSwitchToLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSwitchToLayoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelForecastSectionBottomLayout = new javax.swing.GroupLayout(jPanelForecastSectionBottom);
        jPanelForecastSectionBottom.setLayout(jPanelForecastSectionBottomLayout);
        jPanelForecastSectionBottomLayout.setHorizontalGroup(
            jPanelForecastSectionBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelForecastSectionBottomLayout.createSequentialGroup()
                .addGap(0, 656, Short.MAX_VALUE)
                .addComponent(jButtonSwitchToLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelForecastSectionBottomLayout.setVerticalGroup(
            jPanelForecastSectionBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForecastSectionBottomLayout.createSequentialGroup()
                .addComponent(jButtonSwitchToLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelForecastSectionFormLayout = new javax.swing.GroupLayout(jPanelForecastSectionForm);
        jPanelForecastSectionForm.setLayout(jPanelForecastSectionFormLayout);
        jPanelForecastSectionFormLayout.setHorizontalGroup(
            jPanelForecastSectionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForecastSectionFormLayout.createSequentialGroup()
                .addComponent(jPanelForecastSectionBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, Short.MAX_VALUE))
            .addGroup(jPanelForecastSectionFormLayout.createSequentialGroup()
                .addGroup(jPanelForecastSectionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelForecastSectionTop, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
                    .addComponent(jPanelForecastSectionBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelForecastSectionFormLayout.setVerticalGroup(
            jPanelForecastSectionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForecastSectionFormLayout.createSequentialGroup()
                .addComponent(jPanelForecastSectionTop, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelForecastSectionBody, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelForecastSectionBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCardForm.add(jPanelForecastSectionForm, "card2");

        jPanelLayoutSectionForm.setPreferredSize(new java.awt.Dimension(1004, 400));
        jPanelLayoutSectionForm.setRequestFocusEnabled(false);

        jPanelLayoutSectionTop.setPreferredSize(new java.awt.Dimension(1000, 45));

        jButtonLayoutSectionAdd.setText("+");
        jButtonLayoutSectionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutSectionAddActionPerformed(evt);
            }
        });

        jButtonLayoutSectionSub.setText("-");
        jButtonLayoutSectionSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutSectionSubActionPerformed(evt);
            }
        });

        jLabel3.setText("Type");

        jComboBoxLayoutTypeChoice.setModel(new javax.swing.DefaultComboBoxModel<>(layoutTypeList));

        jButtonSelectDeslectAll.setText("Select/Deselect All");
        jButtonSelectDeslectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectDeslectAllActionPerformed(evt);
            }
        });

        jLabel4.setText("Date");

        javax.swing.GroupLayout jPanelLayoutSectionTopLayout = new javax.swing.GroupLayout(jPanelLayoutSectionTop);
        jPanelLayoutSectionTop.setLayout(jPanelLayoutSectionTopLayout);
        jPanelLayoutSectionTopLayout.setHorizontalGroup(
            jPanelLayoutSectionTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayoutSectionTopLayout.createSequentialGroup()
                .addComponent(jButtonLayoutSectionAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLayoutSectionSub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxLayoutTypeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonSelectDeslectAll)
                .addGap(62, 62, 62)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jPanelLayoutSectionTopLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonLayoutSectionAdd, jButtonLayoutSectionSub});

        jPanelLayoutSectionTopLayout.setVerticalGroup(
            jPanelLayoutSectionTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonSelectDeslectAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelLayoutSectionTopLayout.createSequentialGroup()
                .addGroup(jPanelLayoutSectionTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayoutSectionTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonLayoutSectionAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLayoutSectionSub, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayoutSectionTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBoxLayoutTypeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jXDatePicker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelLayoutSectionTopLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonLayoutSectionAdd, jButtonLayoutSectionSub, jComboBoxLayoutTypeChoice, jLabel3});

        jPanelLayoutSectionBody.setPreferredSize(new java.awt.Dimension(1000, 187));

        jLabel6.setText("Position");

        jSpinnerPosition.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerPositionStateChanged(evt);
            }
        });

        jButtonEditLayoutPreview.setText("Preview Item");
        jButtonEditLayoutPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditLayoutPreviewActionPerformed(evt);
            }
        });

        jLabel10.setText("Parameter Needed");

        jTextAreaParameters.setColumns(20);
        jTextAreaParameters.setRows(5);
        jTextAreaParameters.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextAreaParametersCaretUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaParameters);

        jLabel5.setText("Title");

        jButtonEditLayoutTitle.setText("Edit in HTML Editor");
        jButtonEditLayoutTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditLayoutTitleActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));

        jButtonLayoutSectionLoadLayout.setText("Load Layout & Generate");
        jButtonLayoutSectionLoadLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutSectionLoadLayoutActionPerformed(evt);
            }
        });

        jButtonLayoutSectionSaveLayout.setText("Save Layout");
        jButtonLayoutSectionSaveLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutSectionSaveLayoutActionPerformed(evt);
            }
        });

        jButtonLayoutSectionGenerateNewsletter.setText("Generate Item(s)");
        jButtonLayoutSectionGenerateNewsletter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutSectionGenerateNewsletterActionPerformed(evt);
            }
        });

        jButtonSaveNewsletter.setBackground(new java.awt.Color(0, 255, 51));
        jButtonSaveNewsletter.setText("Save Newsletter");
        jButtonSaveNewsletter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveNewsletterActionPerformed(evt);
            }
        });

        jButtonColorPicker.setText("Color Picker");
        jButtonColorPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorPickerActionPerformed(evt);
            }
        });

        jButtonLayoutSectionLoadLayoutNPreview.setText("Load Layout & Load Preview");
        jButtonLayoutSectionLoadLayoutNPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutSectionLoadLayoutNPreviewActionPerformed(evt);
            }
        });

        jButtonEditLayoutPreviewNewsletter.setText("Preview Newsletter");
        jButtonEditLayoutPreviewNewsletter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditLayoutPreviewNewsletterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayoutSectionBodyLayout = new javax.swing.GroupLayout(jPanelLayoutSectionBody);
        jPanelLayoutSectionBody.setLayout(jPanelLayoutSectionBodyLayout);
        jPanelLayoutSectionBodyLayout.setHorizontalGroup(
            jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayoutSectionBodyLayout.createSequentialGroup()
                .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayoutSectionBodyLayout.createSequentialGroup()
                        .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayoutSectionBodyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonColorPicker)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelLayoutSectionBodyLayout.createSequentialGroup()
                        .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEditLayoutTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerPosition))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLayoutSectionSaveLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSaveNewsletter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayoutSectionBodyLayout.createSequentialGroup()
                        .addComponent(jButtonLayoutSectionLoadLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLayoutSectionLoadLayoutNPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonEditLayoutPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLayoutSectionGenerateNewsletter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditLayoutPreviewNewsletter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jSeparator1)
        );

        jPanelLayoutSectionBodyLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel5, jLabel6});

        jPanelLayoutSectionBodyLayout.setVerticalGroup(
            jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayoutSectionBodyLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayoutSectionBodyLayout.createSequentialGroup()
                        .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jButtonEditLayoutTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayoutSectionBodyLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jButtonColorPicker)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanelLayoutSectionBodyLayout.createSequentialGroup()
                        .addComponent(jButtonLayoutSectionGenerateNewsletter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditLayoutPreview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditLayoutPreviewNewsletter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayoutSectionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLayoutSectionLoadLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLayoutSectionLoadLayoutNPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLayoutSectionSaveLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSaveNewsletter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        jPanelLayoutSectionBodyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel5, jLabel6});

        jPanelLayoutSectionBodyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonEditLayoutTitle, jSpinnerPosition});

        jPanelLayoutSectionBodyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonEditLayoutPreview, jButtonEditLayoutPreviewNewsletter, jButtonLayoutSectionGenerateNewsletter});

        jPanelLayoutSectionBottom.setPreferredSize(new java.awt.Dimension(1000, 100));

        jButtonSwitchToForecast.setText("Switch To Forecast");
        jButtonSwitchToForecast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSwitchToForecastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayoutSectionBottomLayout = new javax.swing.GroupLayout(jPanelLayoutSectionBottom);
        jPanelLayoutSectionBottom.setLayout(jPanelLayoutSectionBottomLayout);
        jPanelLayoutSectionBottomLayout.setHorizontalGroup(
            jPanelLayoutSectionBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayoutSectionBottomLayout.createSequentialGroup()
                .addContainerGap(722, Short.MAX_VALUE)
                .addComponent(jButtonSwitchToForecast, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelLayoutSectionBottomLayout.setVerticalGroup(
            jPanelLayoutSectionBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayoutSectionBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSwitchToForecast, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLayoutSectionFormLayout = new javax.swing.GroupLayout(jPanelLayoutSectionForm);
        jPanelLayoutSectionForm.setLayout(jPanelLayoutSectionFormLayout);
        jPanelLayoutSectionFormLayout.setHorizontalGroup(
            jPanelLayoutSectionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayoutSectionFormLayout.createSequentialGroup()
                .addGroup(jPanelLayoutSectionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayoutSectionFormLayout.createSequentialGroup()
                        .addComponent(jPanelLayoutSectionTop, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayoutSectionFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelLayoutSectionBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelLayoutSectionBody, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLayoutSectionFormLayout.setVerticalGroup(
            jPanelLayoutSectionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayoutSectionFormLayout.createSequentialGroup()
                .addComponent(jPanelLayoutSectionTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLayoutSectionBody, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLayoutSectionBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE))
        );

        jPanelCardForm.add(jPanelLayoutSectionForm, "card3");

        jPanelRoot.add(jPanelCardForm);

        jScrollPane3.setViewportView(jPanelRoot);

        getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLayoutSectionGenerateNewsletterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutSectionGenerateNewsletterActionPerformed
        generateNewsletter();
    }//GEN-LAST:event_jButtonLayoutSectionGenerateNewsletterActionPerformed

    private void jButtonLayoutSectionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutSectionAddActionPerformed
        addLayoutItem();
    }//GEN-LAST:event_jButtonLayoutSectionAddActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButtonChooseDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChooseDirActionPerformed

    private void jButtonSwitchToLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSwitchToLayoutActionPerformed
        switchSectionTo(LAYOUTSECTION);
    }//GEN-LAST:event_jButtonSwitchToLayoutActionPerformed

    private void jButtonSwitchToForecastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSwitchToForecastActionPerformed
        switchSectionTo(FORECASTSECTION);
    }//GEN-LAST:event_jButtonSwitchToForecastActionPerformed

    private void jButtonLayoutSectionSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutSectionSubActionPerformed
        deleteSelectedLayoutItem();
    }//GEN-LAST:event_jButtonLayoutSectionSubActionPerformed

    private void jSpinnerPositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerPositionStateChanged
        layoutFormChanged();
    }//GEN-LAST:event_jSpinnerPositionStateChanged

    private void jTextAreaParametersCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextAreaParametersCaretUpdate
        layoutFormChanged();
    }//GEN-LAST:event_jTextAreaParametersCaretUpdate

    private void jButtonOpenForecastCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenForecastCSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOpenForecastCSVActionPerformed

    private void jButtonEnglishLinkSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnglishLinkSubmitActionPerformed
        submitEnglishLink();
    }//GEN-LAST:event_jButtonEnglishLinkSubmitActionPerformed

    private void jCheckBoxGenerateThisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGenerateThisActionPerformed
        forecastFormChanged();
    }//GEN-LAST:event_jCheckBoxGenerateThisActionPerformed

    private void jButtonEditLayoutPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditLayoutPreviewActionPerformed
        openPreviewHtmlEditor();
    }//GEN-LAST:event_jButtonEditLayoutPreviewActionPerformed

    private void jButtonEditLayoutTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditLayoutTitleActionPerformed
        openTitleHtmlEditor();
    }//GEN-LAST:event_jButtonEditLayoutTitleActionPerformed

    private void jButtonTitleOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTitleOkActionPerformed
        //closeTitleHtmlEditor(true);
    }//GEN-LAST:event_jButtonTitleOkActionPerformed

    private void jButtonTitleCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTitleCancelActionPerformed
        //closeTitleHtmlEditor(false);
    }//GEN-LAST:event_jButtonTitleCancelActionPerformed

    private void jButtonPreviewOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviewOkActionPerformed
        //closePreviewHtmlEditor(true);
    }//GEN-LAST:event_jButtonPreviewOkActionPerformed

    private void jButtonPreviewCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviewCancelActionPerformed
        //closePreviewHtmlEditor(false);
    }//GEN-LAST:event_jButtonPreviewCancelActionPerformed

    private void jButtonLayoutSectionSaveLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutSectionSaveLayoutActionPerformed
        saveLoadCurrentLayout(evt,false);
    }//GEN-LAST:event_jButtonLayoutSectionSaveLayoutActionPerformed

    private void jButtonSelectDeslectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectDeslectAllActionPerformed
        selectDeselectAll();
    }//GEN-LAST:event_jButtonSelectDeslectAllActionPerformed

    private void jButtonLayoutSectionLoadLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutSectionLoadLayoutActionPerformed
        saveLoadCurrentLayout(evt,true);
    }//GEN-LAST:event_jButtonLayoutSectionLoadLayoutActionPerformed

    private void jButtonSaveNewsletterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveNewsletterActionPerformed
        saveNewsletter();
    }//GEN-LAST:event_jButtonSaveNewsletterActionPerformed

    private void jButtonColorPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorPickerActionPerformed
        colorChooser();
    }//GEN-LAST:event_jButtonColorPickerActionPerformed

    private void jButtonLayoutSectionLoadLayoutNPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutSectionLoadLayoutNPreviewActionPerformed
        saveLoadCurrentLayout(evt,false);
    }//GEN-LAST:event_jButtonLayoutSectionLoadLayoutNPreviewActionPerformed

    private void jButtonEditLayoutPreviewNewsletterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditLayoutPreviewNewsletterActionPerformed
        previewNewsletter();
    }//GEN-LAST:event_jButtonEditLayoutPreviewNewsletterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Create Console Window
        if(args.length >0){
            if(args[0].equalsIgnoreCase("-dev"))
                System.out.println("DEV Mode");
        }else{
            openConsole();
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewsLetterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewsLetterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewsLetterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewsLetterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewsLetterUI().setVisible(true);
            }
        });
    }
    private static void openConsole(){
        javax.swing.JFrame jFrameConsoleBox = new javax.swing.JFrame();
        javax.swing.JScrollPane jScrollPaneMessage = new javax.swing.JScrollPane();
        javax.swing.JTextArea jTextAreaMessageBox = new javax.swing.JTextArea();
        
        
        jFrameConsoleBox.getContentPane().setLayout(new javax.swing.BoxLayout(jFrameConsoleBox.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        
        jTextAreaMessageBox.setEditable(false);
        jTextAreaMessageBox.setColumns(100);
        jTextAreaMessageBox.setLineWrap(false);
        jTextAreaMessageBox.setRows(20);
        jTextAreaMessageBox.setWrapStyleWord(true);
        jScrollPaneMessage.setViewportView(jTextAreaMessageBox);
        
        jFrameConsoleBox.getContentPane().add(jScrollPaneMessage);
        jFrameConsoleBox.getContentPane().setSize(1024, 400);
        jFrameConsoleBox.setDefaultCloseOperation(javax.swing.JFrame.HIDE_ON_CLOSE);
        //jFrameConsoleBox.add(new javax.swing.JButton(new OpenAction()));
        jFrameConsoleBox.pack();
        jFrameConsoleBox.setVisible(true);
        
        con = new PrintStream(new TextAreaOutputStream(jTextAreaMessageBox));
        System.setOut(con);
        System.setErr(con);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonChooseDir;
    private javax.swing.JButton jButtonColorPicker;
    public static javax.swing.JButton jButtonEditLayoutPreview;
    public static javax.swing.JButton jButtonEditLayoutPreviewNewsletter;
    public static javax.swing.JButton jButtonEditLayoutTitle;
    private javax.swing.JButton jButtonEnglishLinkSubmit;
    public static javax.swing.JButton jButtonLayoutSectionAdd;
    public static javax.swing.JButton jButtonLayoutSectionGenerateNewsletter;
    public static javax.swing.JButton jButtonLayoutSectionLoadLayout;
    public static javax.swing.JButton jButtonLayoutSectionLoadLayoutNPreview;
    public static javax.swing.JButton jButtonLayoutSectionSaveLayout;
    public static javax.swing.JButton jButtonLayoutSectionSub;
    private javax.swing.JButton jButtonOpenForecastCSV;
    private javax.swing.JButton jButtonPreviewCancel;
    private javax.swing.JButton jButtonPreviewOk;
    private javax.swing.JButton jButtonSaveNewsletter;
    public static javax.swing.JButton jButtonSelectDeslectAll;
    private javax.swing.JButton jButtonSwitchToForecast;
    private javax.swing.JButton jButtonSwitchToLayout;
    private javax.swing.JButton jButtonTitleCancel;
    private javax.swing.JButton jButtonTitleOk;
    public static javax.swing.JCheckBox jCheckBoxGenerateThis;
    public static javax.swing.JColorChooser jColorChooser;
    public static javax.swing.JComboBox<String> jComboBoxLayoutTypeChoice;
    public static javax.swing.JComboBox<String> jComboBoxLayoutTypeChoosen;
    private javax.swing.JDialog jDialogAddLayoutItem;
    public static javax.swing.JDialog jDialogColorChooser;
    public static javax.swing.JEditorPane jEditorPaneLayoutPreview;
    public static javax.swing.JEditorPane jEditorPaneLayoutTitle;
    public static javax.swing.JFileChooser jFileChooserLayout;
    private javax.swing.JFrame jFrameConsoleBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelProgramName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JPanel jPanelCardForm;
    private javax.swing.JPanel jPanelForecastSectionBody;
    private javax.swing.JPanel jPanelForecastSectionBottom;
    private javax.swing.JPanel jPanelForecastSectionForm;
    private javax.swing.JPanel jPanelForecastSectionTop;
    private javax.swing.JPanel jPanelHtmlPreviewButtonsForm;
    private javax.swing.JPanel jPanelHtmlTitleButtonsForm;
    private javax.swing.JPanel jPanelLayoutSectionBody;
    private javax.swing.JPanel jPanelLayoutSectionBottom;
    private javax.swing.JPanel jPanelLayoutSectionForm;
    private javax.swing.JPanel jPanelLayoutSectionTop;
    private javax.swing.JPanel jPanelRoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPaneMessage;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JSpinner jSpinnerPosition;
    private javax.swing.JTabbedPane jTabbedLanguageTab;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextArea jTextAreaEnglishLink;
    private javax.swing.JTextArea jTextAreaMessageBox;
    public static javax.swing.JTextArea jTextAreaParameters;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldChoosingCSVDir;
    public static javax.swing.JTextField jTextFieldColorPicked;
    public static org.jdesktop.swingx.JXDatePicker jXDatePicker;
    // End of variables declaration//GEN-END:variables
}
